export const enum SERVICE_TYPES {
    // Contexts
    DocumentContext,
    PluginContext,
    // Converters,
    PluginDataConverter,
    DataGroupConverter,
    // Data Services
    ExperimentDataGroupDataService,
    ExperimentDataService,
    PackageDataService,
    SettingsDataService,
    SelectTransformPluginsDataService,
    AlgorithmPluginsDataService,
    AlgorithmDataService,
    AlgorithmTrackerDataService,
    VisualizationDataService,
    SelectVisualizationPluginsDataService,
    // Session Services
    FetchSessionService,
    TransformSessionService,
    AlgorithmSessionService,
    VisualizationDataSessionService,
    // Ipc Services
    IpcService,
    // Core Services
    WebService,
    FileService,
    RecorderService,
    // Services
    PackageService,
    ExperimentService,
    FetchService,
    FetchPluginsService,
    DataGroupsService,
    SelectTransformPluginsService,
    TransformService,
    AlgorithmPluginsService,
    AlgorithmSessionOptionsService,
    AlgorithmService,
    DataVisualizationService,
    SelectVisualizationPluginsService,
    VisualizationsService,
    // Consumers
    PackageConsumer,
    ExperimentConsumer,
    FetchPluginsConsumer,
    FetchSessionConsumer,
    DataGroupsConsumer,
    SelectTransformPluginsConsumer,
    TransformSessionConsumer,
    AlgorithmPluginsConsumer,
    AlgorithmSessionConsumer,
    AlgorithmConsumer,
    DataVisualizationSessionConsumer,
    SelectVisualizationPluginsConsumer,
    VisualizationsConsumer,
    // Producers
    PackageProducer,
    ExperimentProducer,
    FetchSessionProducer,
    FetchPluginsProducer,
    DataGroupsProducer,
    SelectTransformPluginsProducer,
    TransformSessionProducer,
    AlgorithmPluginsProducer,
    AlgorithmSessionProducer,
    AlgorithmProducer,
    AlgorithmUpdateProducer,
    AlgorithmTrackerProducer,
    VisualizationDataSessionProducer,
    SelectVisualizationPluginsProducer,
    VisualizationsProducer,
}


